name: powerbook
description: Tooling to combine and render powerd6 books
version: 0.3.5
homepage: https://github.com/powerd6/powerbook
issue_tracker: https://github.com/powerd6/powerbook/issues

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  collection: ^1.16.0
  markdown: ^5.0.0
  slugify: ^2.0.0

dev_dependencies:
  mocktail: ^0.3.0
  lints: ^1.0.0
  test: ^1.16.0
  coverage: ^1.2.0
