name: powerbook
description: Tooling to combine and render powerd6 books
version: 0.0.1
homepage: https://github.com/powerd6/powerbook
license: MIT

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  args: ^2.3.0
  collection: ^1.16.0
  file: ^6.1.2
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
